name: Build playlist

on:
  workflow_dispatch:          # 手动触发仍然保留
  schedule:
    - cron: '0 0 */2 * *'     # 每 2 天的 00:00 触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install deps
        run: |
          python -m pip install -r requirements.txt

      - name: Run crawler
        run: |
          python src/crawler.py

      - name: Commit & push
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name  "GitHub Actions"
          git add playlist.m3u
          git commit -m "chore: update playlist $(date -u '+%Y-%m-%d %H:%M') " || echo "Nothing to commit"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/virtually321/selfview.git
        env:
          # 提前在仓库 Settings → Secrets 设置变量 PAT 为 Personal Access Token
          GIT_AUTHOR_NAME: "actions"
          GIT_COMMITTER_NAME: "actions"
        # 使用 PAT 鉴权
        # 需要在仓库里创建 secret: PAT=ghp_*****
