      - name: Commit & push
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name  "GitHub Actions"
          
          # 拉取远程更改并合并（使用 rebase 保持历史整洁）
          git pull https://${{ secrets.GITHUB_TOKEN }}@github.com/virtually321/selfview.git main --rebase
          
          # 添加更改并提交
          git add playlist.m3u
          git commit -m "chore: update playlist $(date -u '+%Y-%m-%d %H:%M')" || echo "Nothing to commit"
          
          # 强制推送（覆盖远程历史）
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/virtually321/selfview.git main --force
        env:
          GIT_AUTHOR_NAME: "actions"
          GIT_COMMITTER_NAME: "actions"
