- name: Commit and push changes if playlist.m3u changed
  run: |
    git config --global user.email "actions@github.com"
    git config --global user.name "GitHub Actions"

    git pull --no-rebase origin main

    if git diff --quiet playlist.m3u; then
      echo "No changes in playlist.m3u, skipping commit."
      exit 0
    fi

    git add playlist.m3u
    git commit -m "chore: update playlist $(date -u '+%Y-%m-%d %H:%M')"
    git push origin main
