name: Build playlist

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */2 * *'   # UTC时间，每2天0点运行

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      - name: Run crawler
        run: python src/crawler.py

      - name: Commit and push changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          
          # 拉取最新更改并rebase
          git pull --rebase
          
          # 添加更改并提交
          git add playlist.m3u
          git commit -m "chore: update playlist $(date -u '+%Y-%m-%d %H:%M')" || echo "Nothing to commit"
          
          # 强制推送更新
          git push origin main --force
